# Generated by Django 5.2.3 on 2025-07-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='delivery_time',
            field=models.IntegerField(),
        ),
    ]
